updates to the wrapper script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+set -eo pipefail
+module purge
+
 # Author: Vishal Koparde, Ph.D.
 # CCBR, NCI
 # (c) 2021
@@ -9,45 +12,45 @@
 #
 # DISCLAIMER: This wrapper only works on BIOWULF
 
+# setting python and snakemake versions
 PYTHON_VERSION="python/3.7"
 SNAKEMAKE_VERSION="snakemake/5.24.1"
-
-set -eo pipefail
-module purge
-
+# set extra singularity bindings
+EXTRA_SINGULARITY_BINDS="/lscratch, /data/CCBR_Pipeliner/"
 SCRIPTNAME="$0"
+SCRIPTDIRNAME=$(readlink -f $(dirname $0))
 SCRIPTBASENAME=$(readlink -f $(basename $0))
 
-# set extra singularity bindings
-EXTRA_SINGULARITY_BINDS="-B /data/CCBR_Pipeliner/:/data/CCBR_Pipeliner/"
 
 function get_git_commitid_tag() {
+
 # This function gets the latest git commit id and tag
-# Input is PIPELINE_HOME folder which is a git folder
+# @Input:
+#   @param1: PIPELINE_HOME folder which is a initialized git repo folder path
+# @Output:
+#   @param1: tab-delimited commit id and tag
+
   cd $1
   gid=$(git rev-parse HEAD)
   tag=$(git describe --tags $gid 2>/dev/null)
   echo -ne "$gid\t$tag"
+
 }
 
-# ## setting PIPELINE_HOME
 PIPELINE_HOME=$(readlink -f $(dirname "$0"))
 echo "Pipeline Dir: $PIPELINE_HOME"
-# set snakefile
 SNAKEFILE="${PIPELINE_HOME}/workflow/Snakefile"
-
-# get github commit tag
+echo "Snakefile: $SNAKEFILE"
 GIT_COMMIT_TAG=$(get_git_commitid_tag $PIPELINE_HOME)
 echo "Git Commit/Tag: $GIT_COMMIT_TAG"
 
-function usage() { 
+function usage_only() {
 
-# This function prints generic usage of the wrapper script.
+# This script prints only the usage without any pre-amble
 
-    cat << EOF
-${SCRIPTBASENAME}
---> run <Your Pipeline Short Name>
-
+cat << EOF
+#################################################################
+#################################################################
 USAGE:
   bash ${SCRIPTNAME} -m/--runmode=<RUNMODE> -w/--workdir=<WORKDIR>
 Required Arguments:
@@ -58,25 +61,57 @@ Required Arguments:
     *) dryrun : dry run snakemake to generate DAG
     *) unlock : unlock workdir if locked by snakemake
     *) runlocal : run without submitting to sbatch
-2.  WORKDIR: [Type: String]: Absolute or relative path to the output folder with write permissions.
+2.  WORKDIR: [Type: String]: Absolute or relative path to the 
+             output folder with write permissions.
+#################################################################
+#################################################################
 EOF
+
+}
+
+function usage() { 
+
+# This function prints generic usage of the wrapper script.
+# @Input: None
+# @Output: Usage information about the script
+
+cat << EOF
+#################################################################
+#################################################################
+Running ${SCRIPTBASENAME} ...
+<Your Pipeline Short Name>.
+echo "Git Commit/Tag: $GIT_COMMIT_TAG"
+EOF
+
+usage_only
+
 }
 
 function err() { 
 
-# This function print a error message (argument 1), the usage and then exits with non-zero status
+# This is a generic error message function. It prints the message, then the 
+# usage and exits with non-zero exit code.
+# @Input:
+#     @param1: Message to print before printing the usage and exiting
+# @Ouput:
+#     @param2: echo the error message with the usage to the screen
 
 cat <<< "
-#
-#
-#
+#################################################################
+##### ERROR ############ ERROR ########## ERROR #################
+#################################################################
   $@
-#
-#
-#
-" && usage && exit 1 1>&2; 
+" && usage_only && exit 1 1>&2; 
 }
 
+
+function _set_config() {
+
+sed -e "s/PIPELINE_HOME/${PIPELINE_HOME//\//\\/}/g" \
+    -e "s/WORKDIR/${WORKDIR//\//\\/}/g" \
+    ${PIPELINE_HOME}/config/config.yaml > $WORKDIR/config.yaml
+
+}
 
 function init() {
 
@@ -90,79 +125,195 @@ if [ -d $WORKDIR ];then err "Folder $WORKDIR already exists!"; fi
 mkdir -p $WORKDIR
 
 # copy config and samples files
-sed -e "s/PIPELINE_HOME/${PIPELINE_HOME//\//\\/}/g" -e "s/WORKDIR/${WORKDIR//\//\\/}/g" ${PIPELINE_HOME}/config/config.yaml > $WORKDIR/config.yaml
+_set_config
 cp ${PIPELINE_HOME}/config/samples.tsv $WORKDIR/
 
 #create log and stats folders
-if [ ! -d $WORKDIR/logs ]; then mkdir -p $WORKDIR/logs;echo "Logs Dir: $WORKDIR/logs";fi
-if [ ! -d $WORKDIR/stats ];then mkdir -p $WORKDIR/stats;echo "Stats Dir: $WORKDIR/stats";fi
+if [ ! -d $WORKDIR/logs ]; then 
+  mkdir -p $WORKDIR/logs;echo "Logs Dir: $WORKDIR/logs"
+fi
+if [ ! -d $WORKDIR/stats ];then 
+  mkdir -p $WORKDIR/stats;echo "Stats Dir: $WORKDIR/stats"
+fi
 
-echo "Done Initializing $WORKDIR. You can now edit $WORKDIR/config.yaml and $WORKDIR/samples.tsv"
+cat < EOF
+#################################################################
+#################################################################
+Done Initializing $WORKDIR. 
+You can now edit $WORKDIR/config.yaml and $WORKDIR/samples.tsv
+#################################################################
+#################################################################
+EOF
 
 }
 
 function check_essential_files() {
 
 # Checks if files essential to start running the pipeline exist in the workdir
+# By default config.yaml and samples.tsv are considered essential files.
 
   if [ ! -d $WORKDIR ];then err "Folder $WORKDIR does not exist!"; fi
   for f in config.yaml samples.tsv; do
-    if [ ! -f $WORKDIR/$f ]; then err "Error: '${f}' file not found in workdir ... initialize first!";fi
+    if [ ! -f $WORKDIR/$f ]; then 
+      err "Error: '${f}' file not found in workdir ... initialize first!"
+    fi
   done
 
 }
 
 function reconfig(){
+
 # Rebuild config file and replace the config.yaml in the WORKDIR
-# this is only for dev purposes when new key-value pairs are being added to the config file
+# this is only for dev purposes when new key-value pairs are being 
+# updated in the config file in PIPELINE_HOME
 
   check_essential_files
-  sed -e "s/PIPELINE_HOME/${PIPELINE_HOME//\//\\/}/g" -e "s/WORKDIR/${WORKDIR//\//\\/}/g" ${PIPELINE_HOME}/config/config.yaml > $WORKDIR/config.yaml
+  _set_config
   echo "$WORKDIR/config.yaml has been updated!"
 
 }
 
 function runcheck(){
+
 # Check "job-essential" files and load required modules
 
   check_essential_files
   module load $PYTHON_VERSION
   module load $SNAKEMAKE_VERSION
-  SINGULARITY_BINDS="$EXTRA_SINGULARITY_BINDS -B ${PIPELINE_HOME}:${PIPELINE_HOME} -B ${WORKDIR}:${WORKDIR}"
 
 }
 
 function dryrun() {
-# Dry-run
+
+# check essential files, load modules and do Dry-run
 
   runcheck
   run "--dry-run"
+
 }
 
 function unlock() {
-# Unlock the workdir if previous snakemake run ended abruptly
+
+# check essential files, load modules and 
+# unlock the workdir if previous snakemake run ended abruptly
 
   runcheck
-  run "--unlock"  
+  run "--unlock"
+
+}
+
+function _exe_in_path() {
+
+  name_of_exe=$1
+  path_to_exe=$(which $name_of_exe 2>/dev/null)
+ if [ ! -x "$path_to_exe" ] ; then
+    err $path_to_exe NOT FOUND!
+ fi
+
+}
+
+
+function set_singularity_binds(){
+
+# this functions tries find what folders to bind
+# "Biowulf specific"
+# assumes that config.yaml and samples.tsv in the WORKDIR are essential
+# files with the most uptodate information
+# required dos2unix in path
+  _exe_in_path dos2unix
+  echo "$PIPELINE_HOME" > ${WORKDIR}/tmp1
+  echo "$WORKDIR" >> ${WORKDIR}/tmp1
+  grep -o '\/.*' <(cat ${WORKDIR}/config.yaml ${WORKDIR}/samples.tsv)| \
+    dos2unix | \
+    tr '\t' '\n' | \
+    grep -v ' \|\/\/' | \
+    sort | \
+    uniq >> ${WORKDIR}/tmp1
+  grep gpfs ${WORKDIR}/tmp1|awk -F'/' -v OFS='/' '{print $1,$2,$3,$4,$5}' | \
+    grep "[a-zA-Z0-9]" | \
+    sort | uniq > ${WORKDIR}/tmp2
+  grep -v gpfs ${WORKDIR}/tmp1|awk -F'/' -v OFS='/' '{print $1,$2,$3}' | \
+    grep "[a-zA-Z0-9]" | \
+    sort | uniq > ${WORKDIR}/tmp3
+  while read a;do 
+    readlink -f $a
+  done < ${WORKDIR}/tmp3 | grep "[a-zA-Z0-9]"> ${WORKDIR}/tmp4
+  binds=$(cat ${WORKDIR}/tmp2 ${WORKDIR}/tmp3 ${WORKDIR}/tmp4 | sort | uniq | tr '\n' ',')
+  rm -f ${WORKDIR}/tmp?
+  binds=$(echo $binds | awk '{print substr($1,1,length($1)-1)}')
+  SINGULARITY_BINDS="-B $EXTRA_SINGULARITY_BINDS,$binds"
+
+}
+
+function printbinds(){
+
+# set the singularity binds and print them
+# singularity binds are /lscratch,/data/CCBR_Pipeliner,
+# plus paths deduced from config.yaml and samples.tsv using 
+# set_singularity binds function
+
+  set_singularity_binds
+  echo $SINGULARITY_BINDS
+
 }
 
 function runlocal() {
-# If the pipeline is fired up on an interactive node (with sinteractive), this function runs the pipeline
+
+# If the pipeline is fired up on an interactive node (with sinteractive), 
+# this function runs the pipeline
 
   runcheck
+  set_singularity_binds
   if [ "$SLURM_JOB_ID" == "" ];then err "runlocal can only be done on an interactive node"; fi
   module load singularity
   run "local"
+
 }
 
 function runslurm() {
+
 # Submit the execution of the pipeline to the biowulf job scheduler (slurm)
 
   runcheck
+  set_singularity_binds
   run "slurm"
+
 }
 
+function _get_file_modtime() {
+
+# get the modification time for a file
+
+  filename=$1
+  modtime=$(stat $filename|grep Modify|awk '{print $2,$3}'|awk -F"." '{print $1}'|sed "s/ //g"|sed "s/-//g"|sed "s/://g")
+  echo $modtime
+
+}
+
+function create_runinfo() {
+
+# Create a runinfo.yaml file in the WORKDIR
+
+  if [ -f ${WORKDIR}/runinfo.yaml ];then
+    modtime=$(_get_file_modtime ${WORKDIR}/runinfo.yaml)
+    mv ${WORKDIR}/runinfo.yaml ${WORKDIR}/runinfo.yaml.${modtime}
+  fi
+  echo "Pipeline Dir: $PIPELINE_HOME" > ${WORKDIR}/runinfo.yaml
+  echo "Git Commit/Tag: $GIT_COMMIT_TAG" >> ${WORKDIR}/runinfo.yaml
+  userlogin=$(whoami)
+  username=$(finger $userlogin|grep ^Login|awk -F"Name: " '{print $2}')
+  echo "Login: $userlogin" >> ${WORKDIR}/runinfo.yaml
+  echo "Name: $username" >> ${WORKDIR}/runinfo.yaml
+  g=$(groups)
+  echo "Groups: $g" >> ${WORKDIR}/runinfo.yaml
+  d=$(date)
+  echo "Date/Time: $d" >> ${WORKDIR}/runinfo.yaml
+
+}
+
+
 function preruncleanup() {
+
 # Cleanup function to rename/move files related to older runs to prevent overwriting them.
 
   echo "Running..."
@@ -173,7 +324,7 @@ function preruncleanup() {
   cd $WORKDIR
   ## Archive previous run files
   if [ -f ${WORKDIR}/snakemake.log ];then 
-    modtime=$(stat ${WORKDIR}/snakemake.log |grep Modify|awk '{print $2,$3}'|awk -F"." '{print $1}'|sed "s/ //g"|sed "s/-//g"|sed "s/://g")
+    modtime=$(_get_file_modtime ${WORKDIR}/snakemake.log)
     mv ${WORKDIR}/snakemake.log ${WORKDIR}/stats/snakemake.${modtime}.log
     if [ -f ${WORKDIR}/snakemake.log.HPC_summary.txt ];then 
       mv ${WORKDIR}/snakemake.log.HPC_summary.txt ${WORKDIR}/stats/snakemake.${modtime}.log.HPC_summary.txt
@@ -186,6 +337,8 @@ function preruncleanup() {
   if [ "$nslurmouts" != "0" ];then
     for f in $(ls ${WORKDIR}/slurm-*.out);do mv ${f} ${WORKDIR}/logs/;done
   fi
+
+  create_runinfo
 
 }
 
@@ -289,6 +442,7 @@ snakemake $1 -s $SNAKEFILE \
 }
 
 function reset() {
+
 # Delete the workdir and re-initialize it
 
   echo "Working Dir: $WORKDIR"
@@ -297,16 +451,17 @@ function reset() {
   rm -rf $WORKDIR
   echo "Re-Initializing $WORKDIR"
   init
+
 }
 
 
 function main(){
+
 # Main function which parses all arguments
 
-  if [ $# -eq 0 ]; then usage; exit 1; fi
+  if [ $# -eq 0 ]; then usage && exit 1; fi
 
-  for i in "$@"
-  do
+  for i in "$@"; do
   case $i in
       -m=*|--runmode=*)
         RUNMODE="${i#*=}"
@@ -332,8 +487,10 @@ function main(){
     dry) dryrun && exit 0;;                      # hidden option
     local) runlocal && exit 0;;                  # hidden option
     reconfig) reconfig && exit 0;;               # hidden option for debugging
+    printbinds) printbinds && exit 0;;           # hidden option
     *) err "Unknown RUNMODE \"$RUNMODE\"";;
   esac
+
 }
 
 # call the main function
